# Generated by Django 2.2.2 on 2020-03-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachername', models.CharField(max_length=50)),
                ('studentgroup', models.CharField(max_length=50)),
                ('endroll', models.IntegerField(max_length=50)),
                ('startroll', models.IntegerField(max_length=50)),
            ],
        ),
    ]
