# Generated by Django 2.2.2 on 2020-03-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='endroll',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='startroll',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='studentgroup',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
