# Generated by Django 2.2.2 on 2020-03-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20200323_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='studentgroup',
            field=models.CharField(max_length=50),
        ),
    ]
