# Generated by Django 2.2.2 on 2020-03-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20200323_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='endrolllate',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='startrolllate',
            field=models.IntegerField(default=0, max_length=50),
        ),
    ]
