# Generated by Django 2.2.2 on 2020-03-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectname', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=50)),
                ('subjectcode', models.CharField(max_length=50)),
                ('teachername', models.CharField(max_length=50)),
                ('studentgroup', models.CharField(max_length=50)),
            ],
        ),
    ]
