# Generated by Django 2.2.2 on 2020-06-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0002_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='attendanceDateTime',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
