# Generated by Django 2.2.6 on 2019-11-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('answertext', models.TextField()),
                ('answeredby', models.CharField(max_length=50)),
                ('qid', models.IntegerField()),
                ('answereddate', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('questiontext', models.TextField()),
                ('askedby', models.CharField(max_length=50)),
                ('pasteddate', models.CharField(max_length=30)),
            ],
        ),
    ]
