# Generated by Django 2.2.6 on 2019-11-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentzone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6)),
                ('address', models.TextField()),
                ('rollno', models.CharField(max_length=15)),
                ('contactno', models.CharField(max_length=15)),
                ('emailaddress', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('complaintext', models.TextField()),
                ('complaindate', models.CharField(max_length=30)),
            ],
        ),
    ]
