# Generated by Django 2.2.6 on 2019-11-24 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentzone', '0002_complain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='emailaddress',
        ),
    ]
