# Generated by Django 2.2.6 on 2019-11-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('contact_no', models.CharField(max_length=15)),
                ('emailaddress', models.EmailField(max_length=254)),
                ('enquirytext', models.TextField()),
                ('enquirydate', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('userid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('usertype', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6)),
                ('address', models.TextField()),
                ('nationality', models.CharField(max_length=50)),
                ('contactno', models.CharField(max_length=50)),
                ('emailaddress', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('connectdate', models.CharField(max_length=20)),
            ],
        ),
    ]
