# Generated by Django 2.2.6 on 2019-11-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalzone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='rollno',
            field=models.CharField(default=0, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='emailaddress',
            field=models.CharField(max_length=50),
        ),
    ]
