# Generated by Django 2.2.6 on 2019-11-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalzone', '0003_auto_20191126_0605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('imagefile', models.FileField(null=True, upload_to='images/', verbose_name='')),
            ],
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='imagename',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='videofile',
        ),
    ]
