# Generated by Django 2.2.6 on 2019-11-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalzone', '0004_auto_20191126_1307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='display_picture',
            field=models.FileField(default=2121, upload_to=''),
            preserve_default=False,
        ),
    ]
