# Generated by Django 2.2.6 on 2019-11-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalzone', '0005_auto_20191126_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='display_picture',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='file',
            field=models.FileField(default=788, upload_to='images/'),
            preserve_default=False,
        ),
    ]
