# Generated by Django 2.2.2 on 2020-03-01 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('generalzone', '0006_auto_20191127_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinfo',
            old_name='nationality',
            new_name='branch',
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='connectdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
