# Generated by Django 2.2.2 on 2020-03-01 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generalzone', '0008_auto_20200301_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinfo',
            old_name='nationality',
            new_name='branch',
        ),
    ]
