# Generated by Django 2.2.2 on 2020-03-01 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generalzone', '0010_auto_20200301_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='datee',
        ),
    ]
