# Generated by Django 2.2.2 on 2020-08-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalzone', '0012_studentinfo_connectdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
