# Generated by Django 2.2.2 on 2020-08-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalzone', '0013_studentinfo_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='semester',
            field=models.IntegerField(default=0),
        ),
    ]
